# Generated by Django 4.1 on 2022-08-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=225, verbose_name='nome_cliente')),
                ('sobrenome_cliente', models.CharField(max_length=225, verbose_name='sobrenome_cliente')),
                ('email_cliente', models.CharField(max_length=225, verbose_name='email_cliente')),
                ('data_nascimento_cliente', models.DateField(blank=True, null=True, verbose_name='data_nascimento_cliente')),
                ('CPF_cliente', models.CharField(max_length=225, verbose_name='CPF_cliente')),
                ('is_Produtor', models.BooleanField(verbose_name='is_Produtor')),
                ('tipo_produto', models.CharField(max_length=200, verbose_name='tipo_produto')),
            ],
        ),
    ]
