# Generated by Django 4.1 on 2022-08-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_pequi',
            name='is_CNPJ',
            field=models.BooleanField(null=True, verbose_name='is_CNPJ'),
        ),
        migrations.AlterField(
            model_name='usuario_pequi',
            name='is_Produtor',
            field=models.BooleanField(null=True, verbose_name='is_Produtor'),
        ),
    ]
