# Generated by Django 4.1 on 2022-08-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_delete_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_contato', models.CharField(max_length=225, verbose_name='nome_produto')),
                ('email_contato', models.CharField(max_length=225, verbose_name='nome_produto')),
                ('is_wpp', models.BooleanField(verbose_name='is_wpp')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua_endereco', models.CharField(max_length=225, verbose_name='nome_produto')),
                ('CEP_endereco', models.CharField(max_length=225, verbose_name='CEP_endereco')),
                ('bairro_endereco', models.CharField(max_length=225, verbose_name='bairro_endereco')),
                ('cidade_endereco', models.CharField(max_length=225, verbose_name='cidade_endereco')),
                ('estado_endereco', models.CharField(max_length=225, verbose_name='estado_endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=225, verbose_name='nome_produto')),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='preco_produto')),
                ('descricao_produto', models.CharField(blank=True, max_length=225, null=True, verbose_name='descricao_produto')),
                ('quantidade_produto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='quantidade_produto')),
                ('imagem_produto', models.ImageField(blank=True, null=True, upload_to='core', verbose_name='imagem_produto')),
                ('tipo_produto', models.CharField(max_length=200, verbose_name='tipo_produto')),
            ],
        ),
    ]
