# Generated by Django 4.1 on 2022-08-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_id_user_produtor_produto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='ID_User_Produtor_Produto',
            new_name='id_user_produtor',
        ),
    ]
