# Generated by Django 4.1 on 2022-08-29 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_produto_user_produtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='CEP_endereco',
            field=models.CharField(max_length=225, null=True, verbose_name='CEP_endereco'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='bairro_endereco',
            field=models.CharField(max_length=225, null=True, verbose_name='bairro_endereco'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='cidade_endereco',
            field=models.CharField(max_length=225, null=True, verbose_name='cidade_endereco'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='estado_endereco',
            field=models.CharField(max_length=225, null=True, verbose_name='estado_endereco'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='rua_endereco',
            field=models.CharField(max_length=225, null=True, verbose_name='rua_endereco'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='user_endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
