# Generated by Django 4.1 on 2022-08-30 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_endereco_cep_endereco_endereco_bairro_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='email_contato',
            field=models.CharField(max_length=225, null=True, verbose_name='email_contato'),
        ),
        migrations.AddField(
            model_name='contato',
            name='is_wpp',
            field=models.BooleanField(null=True, verbose_name='is_wpp'),
        ),
        migrations.AddField(
            model_name='contato',
            name='telefone_contato',
            field=models.CharField(max_length=225, null=True, verbose_name='telefone_contato'),
        ),
        migrations.AddField(
            model_name='contato',
            name='user_contato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
