# Generated by Django 4.1 on 2022-08-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contato_email_contato_contato_is_wpp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo_produto',
            field=models.CharField(choices=[('alimento', 'Alimento'), ('bebidas', 'Bebida'), ('cosmetico', 'Cosmetico'), ('vestimenta', 'Vestimenta'), ('outros', 'Outros')], max_length=200, null=True, verbose_name='tipo_produto'),
        ),
    ]
