# Generated by Django 4.1 on 2022-09-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='produto',
            new_name='produto_rating',
        ),
        migrations.RenameField(
            model_name='reviewrating',
            old_name='usuario',
            new_name='usuario_rating',
        ),
    ]
