# Generated by Django 4.1 on 2022-09-05 17:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_rename_produto_reviewrating_produto_rating_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewRating',
            new_name='ProdutoReview',
        ),
    ]
