# Generated by Django 4.1 on 2022-09-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_produtoreview_texto_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoreview',
            name='nota_avaliacao',
            field=models.FloatField(null=True),
        ),
    ]
