# Generated by Django 4.1 on 2022-09-11 23:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_profile_timestamp_profile_total_profile_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Cart',
        ),
    ]
