# Generated by Django 4.0 on 2022-09-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cart_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='core.Produto'),
        ),
        migrations.AlterField(
            model_name='produtoreview',
            name='nota_avaliacao',
            field=models.FloatField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True),
        ),
    ]
